// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjPohsSRuTKknQ6iK8ZY8kun3PlkqqPVk',
    appId: '1:1079805540348:web:ea4f230442b9864476e479',
    messagingSenderId: '1079805540348',
    projectId: 'pelgrim-872f5',
    authDomain: 'pelgrim-872f5.firebaseapp.com',
    storageBucket: 'pelgrim-872f5.appspot.com',
    measurementId: 'G-VLFCK2WSY1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyAjPohsSRuTKknQ6iK8ZY8kun3PlkqqPVk",
      authDomain: "pelgrim-872f5.firebaseapp.com",
      projectId: "pelgrim-872f5",
      storageBucket: "pelgrim-872f5.appspot.com",
      messagingSenderId: "1079805540348",
      appId: "1:1079805540348:web:ea4f230442b9864476e479",
      measurementId: "G-VLFCK2WSY1");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwUphJKFSO7I6_Z86A-5Xl-oVi5T7ives',
    appId: '1:1079805540348:android:54ff8d77c21ff03c76e479',
    messagingSenderId: '1079805540348',
    projectId: 'pelgrim-872f5',
    storageBucket: 'pelgrim-872f5.appspot.com',
  );
}
